name: grype-explicit-scan
kind: workflow
apiVersion: automation.cloudbees.io/v1alpha1
on:
  workflow_dispatch:
permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write
jobs:
  grype-scan:
    steps:
      - name: checkout Source Code
        uses: cloudbees-io/checkout@v1
      - name: Scan with grype
        with:
          binary-tar-path: ./alpine.tar
        uses: cloudbees-io/grype-plugin@v1
